[package]
name = "algo-rs"
version = "0.1.0"
authors = ["nagitausu <nagitaosu.radio@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
rand = "0.7.3"
itertools = "0.8.2"
maplit = "1.0.2"
